title: MobiKit
author:
  name: Name Lastname
  email: hello@example.com
description: > # this means to ignore newlines
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results).
type: free # Choose one from "open source", "free", freemium, ad supported, commercial
google_analytics: UA-NNNNNNNN-N
links:
  app_store: https://apps.apple.com/
  google_play: https://play.google.com/
theme: mobikit
plugins:
 - jekyll-seo-tag
